### PR TITLE
WIP: Add include for stdint.h to bring in uint8_t

### PR DESCRIPTION
**Pull request by FoundationKen**

### CODE REVIEW

**Comment by FoundationKen** [comment]
Found another missing .h, and some changes to Makefile.in.  Will update this PR soon.

**Comment by ksedgwic** [comment]
> @ksedgwic You'll need to sign the commit used for this PR.

@FoundationKen, I think @wolfmcnally  meant you.

Nice to meet you!

**Comment by FoundationKen** [comment]
There are other changes that will be required to make the WIndows build work, but this is necessary, so we may as well push it.  I've never signed a commit before.  I'll get setup for that and figure out what I need to change.

**Comment by FoundationKen** [comment]
> > @ksedgwic You'll need to sign the commit used for this PR.
> 
> @FoundationKen, I think @wolfmcnally meant you.
> 
> Nice to meet you!

Likewise!

**Comment by ChristopherA** [comment]
@FoundationKen: Any progress on signing this commit? We are trying to be careful of provenance and security. I can override, or @wolfmcnally can redo the commit with him as author of record.

**Comment by FoundationKen** [comment]
Sorry...I haven't had a chance to look into that yet.  So busy with the new
hardware now.  You can certainly go ahead and resubmit it.

**Comment by wolfmcnally** [comment]
I created a signed commit and PR #28 that duplicates this, so I'm closing it.

**Pull request closed without merging**
