### PR TITLE
HKDF_256 and random number generation

### PR DESCRIPTION
**Pull request by wolfmcnally**
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Added HKDF_256 and random number generation functions.	ba1b793	Wolf McNally <wolf@wolfmcnally.com>	Apr 4, 2020 at 11:52 PM
-----BEGIN PGP SIGNATURE-----
Comment: GPGTools - https://gpgtools.org

iQIzBAEBCgAdFiEElDZS7jhEF2DD3DU2S2wvz4lHgK4FAl6JgGwACgkQS2wvz4lH
gK5CZw/8C9J0m2HBsxP+iFuYhn8mQyFFp2mlw7NtkLB9JjCPnAx/gRCkhaJaSViU
N5d7vV3QqOCYGv7lYaD9EjuBxqlzV+En4hEmElcpzYIalvNlRUKFfQaR//X3iNdC
TzIwcAu03tKm2s7XiYxbjidUgrBYE1+vz3AyycKbkog+FUx/Czkv+XBetTTEH365
o05hyg8NTZljGCTseZRfyFGn8DWoeYMQ2epTvKwjV9MimMyQGzFfeB7EAH6jlQoz
UjMIVpCVToqTqO25JWC7CGYo/UDNpOz6yPDECFl0IMgSPY5889cC7hPgscQdO+E6
L8N5hoSUuW6vvtocKH+W8O6Y7qbFTVgX377dJlF6r9Y/VE9c3jwQaW3WKgxpK3Be
DxLhiclC/tlLIqGBvU0gYn8L+riorTSEdDd59BSTRwI1KFcbuxu/LTJIuNdW1qr6
NkmrtCpFVypwYknsEOwsBpoSaTSsoJXoVyuAwcgbBnnPm96Xbdhl0oJ8eM/eScN8
Dx3IoMLeEX2inwpBTI4mqHhH4rYOSQGdBX9R5XGisHBoAu1fKMpIbc9J84u+lYsa
nX1+QqHa8mhDi8s8DYv+vTyzIouxIqn86QnsnuomP1QZXbvqeOrcMryk044K14ga
Vznivb37zha/0cUBvyISIc1gt7UuYQPjEVw9kpyGkl4o6vgjYcM=
=uN7l
-----END PGP SIGNATURE-----

### CODE REVIEW

**Comment by ChristopherA** [comment]
We should chat with @maaku (and maybe @kanzure) about best practices for submitting PRs to this repo. This, and SLIP39, are our most sensitive repos as we'll have to pay to have them formally audited. For this particular repo, 90%+ of the time we can say "we don't need file X reviewed because it comes from COMMIT that was reviewed by someone else/is a well known reviewed file".

A few problems from the perspective of a outside reviewer who wants to see us doing careful git control is that we need to also show thoughtful discussion. 

So a few problems with this PR:

* It adds too many files at once. Ideally, it should only add specific files from one source.
* The PR description itself doesn't describe well the reason why these specific files is being added from the source.
  * That these additions are being used or will be used by at least one other of our projects.
  * That we likely be using them in multiple projects in the future.
  * That this addition doesn't unnecessarily duplicate features of another set of files in `bc-base-crypto`, or in other of our repos.
* It doesn't have changes in the readme to know here these files came from, which commit, and their authors and copyright.
* Ideally there should be some acknowledgement by community in the comments of a single source PR that adding from this particular choice is the best choice.
* It should ideally be approved not only by myself, but also someone with more up-to-date cryptographic code chops than I, for instance @maaku.
* If it changes the original source, that should noted, as it requires additional scrutiny. I'm not against even major changes to an original choice, it just requires even more scrutiny. These changes to a single source possibly should be added in a separate PR for community commentary.

I don't believe we have to hold to these practices for all of our repos, only the important ones with cryptographic code in them, such as bc-shamir.

Completely separately from this as general policy, I am a bit confused on the files being added. I thought we decided in signal not to do mersienne-twister and only update pbkdf2.c with new functionality.

cc/ @maaku @ksedgwic @kanzure

-- Christopher Allen

**Comment by kanzure** [comment]
I would be curious about a few things:

* Where did this code come from- was it from another library? Has that library been audited or formally reviewed?
* Are there any alternatives, and is this one superior to the alternatives available?
* If this is new code, then what is the appropriate amount of testing that should be done? What is the expected appropriate level of review?

**Comment by ksedgwic** [comment]
I think your concerns are valid and measured.

**Comment by wolfmcnally** [comment]
> Can you add this PR the URLs to the sources for these new files for us to review?

Done.

**Comment by wolfmcnally** [comment]
@ChristopherA I'm going to withdraw this PR and make simpler, more specific commits. Please let me know exactly what you'd like added and in what order.

**Pull request closed without merging**
